version: '3.1'
services:
  mongo:
    image: mongo:7.0.11
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpw
    networks:
      - mongo-db-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpw
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpw@mongo:27017/
    networks:
      - mongo-db-net


networks:
  mongo-db-net:
    driver: bridge
